name: debug

on:
  schedule:
    - cron: '30 4 * * *'

  workflow_dispatch:

jobs:
  run_r_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2


      - name: Get fresh Dropbox access token from script
        run: |
          export APP_KEY="${{ secrets.DROPBOX_APP_KEY }}"
          export APP_SECRET="${{ secrets.DROPBOX_APP_SECRET }}"
          export REFRESH_TOKEN="${{ secrets.DROPBOX_REFRESH_TOKEN }}"
          bash codes/refresh_token.sh
          
      - name: Debug Access Token (nicht für Produktion)
        run: |
          echo "Access Token (erste 10 Zeichen): ${DROPBOX_ACCESS_TOKEN:0:10}"
