name: Run travel_time_google and upload to Dropbox

on:
  schedule:
    # Morgens (MESZ: 05:30 bis 09:00 alle 15 Min → UTC minus 129 Min)
    - cron: '21 3 * * *'   # 05:30 MESZ
    - cron: '36 3 * * *'   # 05:45 MESZ
    - cron: '51 3 * * *'   # 06:00 MESZ
    - cron: '06 4 * * *'   # 06:15 MESZ
    - cron: '21 4 * * *'   # 06:30 MESZ
    - cron: '36 4 * * *'   # 06:45 MESZ
    - cron: '51 4 * * *'   # 07:00 MESZ
    - cron: '06 5 * * *'   # 07:15 MESZ
    - cron: '21 5 * * *'   # 07:30 MESZ
    - cron: '36 5 * * *'   # 07:45 MESZ
    - cron: '51 5 * * *'   # 08:00 MESZ
    - cron: '06 6 * * *'   # 08:15 MESZ
    - cron: '21 6 * * *'   # 08:30 MESZ
    - cron: '36 6 * * *'   # 08:45 MESZ
    - cron: '51 6 * * *'   # 09:00 MESZ

    # Nachmittags (MESZ: 14:30 bis 18:00 → UTC minus 129 Min)
    - cron: '21 12 * * *'  # 14:30 MESZ
    - cron: '36 12 * * *'  # 14:45 MESZ
    - cron: '51 12 * * *'  # 15:00 MESZ
    - cron: '06 13 * * *'  # 15:15 MESZ
    - cron: '21 13 * * *'  # 15:30 MESZ
    - cron: '36 13 * * *'  # 15:45 MESZ
    - cron: '51 13 * * *'  # 16:00 MESZ
    - cron: '06 14 * * *'  # 16:15 MESZ
    - cron: '21 14 * * *'  # 16:30 MESZ
    - cron: '36 14 * * *'  # 16:45 MESZ
    - cron: '51 14 * * *'  # 17:00 MESZ
    - cron: '06 15 * * *'  # 17:15 MESZ
    - cron: '21 15 * * *'  # 17:30 MESZ
    - cron: '36 15 * * *'  # 17:45 MESZ
    - cron: '51 15 * * *'  # 18:00 MESZ

  workflow_dispatch:  # manueller Start


jobs:
  run_r_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies for RCurl
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libjpeg-dev libjq-dev jq

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: renv/library
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: ${{ runner.os }}-renv-

      - name: Install renv and restore packages
        run: |
          install.packages("renv")
          renv::restore()
        shell: Rscript {0}

      - name: Run R script and capture output filename
        id: runscript
        run: |
          Rscript codes/travel_time_google.R
          FILE_NAME=$(cat output_filename.txt)
          echo "FILE_NAME=$FILE_NAME" >> $GITHUB_ENV

      - name: Get fresh Dropbox access token from script
        run: |
          export APP_KEY="${{ secrets.DROPBOX_APP_KEY }}"
          export APP_SECRET="${{ secrets.DROPBOX_APP_SECRET }}"
          export REFRESH_TOKEN="${{ secrets.DROPBOX_REFRESH_TOKEN }}"
          bash codes/refresh_token.sh

      - name: Upload file to Dropbox
        run: |
          curl -X POST https://content.dropboxapi.com/2/files/upload \
            --header "Authorization: Bearer ${{ env.DROPBOX_ACCESS_TOKEN }}" \
            --header "Dropbox-API-Arg: {\"path\": \"/funstuff/pendeln/output_git/${{ env.FILE_NAME }}\", \"mode\": \"overwrite\"}" \
            --header "Content-Type: application/octet-stream" \
            --data-binary @output_git/${{ env.FILE_NAME }}
