name: Run travel_time_google

on:
  schedule:
    - cron: '30 5 * * *'  # UTC time (5:30 UTC = 6:30 CET in winter, 7:30 in summer)
  workflow_dispatch:  # Optional: lets you run it manually from GitHub

jobs:
  run_r_script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        run: |
          Rscript -e 'install.packages(c("httr", "jsonlite", "lubridate", "tidyverse"))'

      - name: Run script
        run: Rscript codes/travel_time_google.R
