name: Run travel_time_google and upload to Dropbox

on:
  schedule:
    - cron: '30 4 * * *'   # 05:30 CET
    - cron: '0 5 * * *'    # 06:00
    - cron: '30 5 * * *'   # 06:30
    - cron: '0 6 * * *'    # 07:00
    - cron: '30 6 * * *'   # 07:30
    - cron: '0 7 * * *'    # 08:00
    - cron: '0 14 * * *'   # 15:00
    - cron: '30 14 * * *'  # 15:30
    - cron: '0 15 * * *'   # 16:00
    - cron: '30 15 * * *'  # 16:30
    - cron: '0 16 * * *'   # 17:00
    - cron: '30 16 * * *'  # 17:30
    - cron: '0 17 * * *'   # 18:00
  workflow_dispatch:

jobs:
  run_r_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies for RCurl
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: renv/library
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: ${{ runner.os }}-renv-

      - name: Install renv and restore packages
        run: |
          install.packages("renv")
          renv::restore()
        shell: Rscript {0}

      - name: Run R script and capture output filename
        id: runscript
        run: |
          FILE_NAME=$(Rscript codes/travel_time_google.R)          

      - name: Upload file to Dropbox
        run: |
          curl -X POST https://content.dropboxapi.com/2/files/upload \
            --header "Authorization: Bearer ${{ secrets.DROPBOX_TOKEN }}" \
            --header "Dropbox-API-Arg: {\"path\": \"/funstuff/pendeln/output_git/${{ env.FILE_NAME }}\", \"mode\": \"overwrite\"}" \
            --header "Content-Type: application/octet-stream" \
            --data-binary @output_git/${{ env.FILE_NAME }}
